version: "2"

services:
  image_ai:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - "./data:/data"
    tty: true
    environment:
      TZ: Asia/Tokyo
      FLASK_APP: server.py
      FLASK_ENV: development
    command: flask run --host 0.0.0.0 --port 8888
